social_network/apps/account/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'account'
urlpatterns = [
    path('account/', views.user_account, name = 'user_account'),
    path('account_setting/', views.account_setting, name = 'account_setting'),
    path('friends/', views.friends, name = 'friends'),
    path('friend_request/', views.friend_request, name = 'friend_request'),
    path('id<int:account_id>/add_friend', views.add_friend, name = 'add_friend'),
    path('id<int:account_id>/add_follower', views.add_follower, name = 'add_follower'),
    path('confirm_friend<int:account_id>/', views.confirm_friend, name = 'confirm_friend'),
    path('delete_friend<int:account_id>/', views.delete_friend, name = 'delete_friend'),
    path('delete_follower<int:account_id>/', views.delete_follower, name = 'delete_follower'),
    path('users/', views.find_users, name = 'find_users'),
    path('id<int:account_id>/', views.account, name = 'account'),
    path('/<str:arg2>/', views.text2image, name='text2image'),
    ]

social_network/apps/dialogs/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'dialogs'
urlpatterns = [
    path('dialog/<str:username>/', views.dialog, name = 'dialog'),
    path('dialog/<str:reciever_name>/leave_message/', views.leave_message, name = 'leave_message'),
    path('messages/', views.messages, name = 'messages'),
    path('post<str:username>/', views.post, name = 'post'),
    path('new_messages/', views.new_messages, name = 'new_messages'),
    path('message<int:message_id>/delete/', views.delete_message, name = 'delete_message'),
    path('dialog<int:companion_id>/delete/', views.delete_dialog, name = 'delete_dialog'),
    ]

social_network/apps/registration/urls.py
from django.urls import path
from django.contrib.auth import views as standart_views

from . import views

app_name = 'registration'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('login/', standart_views.LoginView.as_view(), name='login'),
    path('logout/', standart_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.register, name = 'register'),
    ]

social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import json
import time
import requests
import base64

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('registration.urls')),
    path('', include('account.urls')),
    path('', include('dialogs.urls')),
    path('', include('posts.urls')),
    path('', include('bots.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/apps/account/models.py
from django.db import models

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.utils import timezone
from datetime import datetime, timedelta


class Profile(models.Model):
    GENDER_CHOICE = (
    ("M", "М"),
    ("F", "Ж"),
    (None, "-")
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField('Аватар', blank=True, upload_to = 'images/avatar/')
    gender =  models.CharField('Пол', max_length=1,
                  choices=GENDER_CHOICE,
                  blank=True)
    city = models.CharField('Город', max_length=100, blank=True)
    birth_date = models.DateField('Дата рождения', null=True, blank=True)
    father_name = models.CharField('Отчество', max_length=100, blank=True)
    achivments = models.CharField('Достижения', max_length=1000, blank=True)
    interes = models.CharField('Интересы', max_length=1000, blank=True)
    scout = models.IntegerField(default=0)
    rescuer = models.IntegerField(default=0)
    defender = models.IntegerField(default=0)
    hero = models.IntegerField(default=0)
    ivents = models.IntegerField(default=0)
    behavior = models.IntegerField(default=0)
    sum_points = models.IntegerField(default=0)



    
    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Status(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    online = models.DateTimeField('Был в онлайне', null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def get_online_status(self):
        status = ''
        timezone_delta = timedelta(hours=3, minutes=0)
        online_status_true = timedelta(minutes=5)
        user_online = self.online + timezone_delta

        if self.user.profile.gender == 'F':
            if user_online.date() == (datetime.now() - timedelta(days=1)).date():
                status = 'Была онлайн вчера в ' + user_online.time().strftime("%H:%M")
            elif timezone.now() - self.online < online_status_true:
                status = 'Онлайн'
            elif user_online.date() == datetime.now().date():
                status = 'Была онлайн сегодня в ' + user_online.time().strftime("%H:%M")
            elif user_online.date().year == datetime.now().date().year:
                status = 'Была онлайн ' + user_online.date().strftime("%d.%m") + ' в ' + user_online.time().strftime("%H:%M")
            else:
                status = 'Была онлайн ' + user_online.date().strftime("%d.%m.%Y") + ' в ' + user_online.time().strftime("%H:%M")
        else:
            if user_online.date() == (datetime.now() - timedelta(days=1)).date():
                status = 'Был онлайн вчера в ' + user_online.time().strftime("%H:%M")
            elif timezone.now() - self.online < online_status_true:
                status = 'Онлайн'
            elif user_online.date() == datetime.now().date():
                status = 'Был онлайн сегодня в ' + user_online.time().strftime("%H:%M")
            elif user_online.date().year == datetime.now().date().year:
                status = 'Был онлайн ' + user_online.date().strftime("%d.%m") + ' в ' + user_online.time().strftime("%H:%M")
            else:
                status = 'Был онлайн ' + user_online.date().strftime("%d.%m.%Y") + ' в ' + user_online.time().strftime("%H:%M")
        return status

    class Meta:
        verbose_name = 'Статус'
        verbose_name_plural = 'Статусы'


class Friend(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    users_friend = models.ForeignKey(User, related_name = 'users_friend', on_delete = models.CASCADE)
    confirmed = models.BooleanField('Подтверждено', default=False)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Друг'
        verbose_name_plural = 'Друзья'


class Follower(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    follower_for = models.ForeignKey(User, related_name = 'follower_for', on_delete = models.CASCADE)

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

social_network/apps/account/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar', 'gender', 'city', 'birth_date')

social_network/apps/account/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from .models import Friend, Follower
from posts.forms import PostForm
from posts.models import Post
from django.utils import timezone
from .forms import ProfileForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
import time
import requests
import base64

#Аккаунт пользователя
@login_required(login_url = '/')
def user_account(request):
    username = request.user
    user = User.objects.get(username = username)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.post_time = timezone.now()
            new_post.save()
            return HttpResponseRedirect(request.path)
    else:
        form = PostForm()

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    followers = Follower.objects.filter(follower_for = request.user)
    context = {'user': user, 'form':form, 'user_posts': post_list, 'followers': followers}
    return render(request, 'account/account.html', context)

#Изменение аватара пользователя
@login_required(login_url = '/')
def account_setting(request):
    user_set = User.objects.get(id = request.user.id)
    print(user_set.profile.city)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user_set.profile)
        if form.is_valid():
            user_setting = request.user
            first_name = request.POST.get('first_name')
            last_name = request.POST.get('last_name')
            avatar = form.cleaned_data['avatar']
            gender = form.cleaned_data['gender']
            city = form.cleaned_data['city']
            birth_date = form.cleaned_data['birth_date']
            if avatar:
                user_setting.profile.avatar = avatar
            else:
                user_setting.profile.avatar = 'images/avatar/standart.jpg'
            user_setting.profile.gender = gender
            user_setting.profile.city = city
            user_setting.profile.birth_date = birth_date
            if first_name:
                user_setting.first_name = first_name
            if last_name:
                user_setting.last_name = last_name
            user_setting.save()
            return HttpResponseRedirect(reverse('account:user_account'))
    else:
        form = ProfileForm(instance=user_set.profile)
    context = {'form': form}
    return render(request, 'account/setting.html', context)


@login_required(login_url = '/')
def friends(request):
    users_friends1 = Friend.objects.filter(user = request.user, confirmed = True)
    users_friends2 = Friend.objects.filter(users_friend = request.user, confirmed = True)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"friends1": users_friends1, "friends2": users_friends2, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friends.html', context)


@login_required(login_url = '/')
def friend_request(request):
    not_confirmed_friends = Friend.objects.filter(users_friend = request.user, confirmed = False)
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {"not_confirmed_friends": not_confirmed_friends, "not_confirmed_friends_count": new_friends}
    return render(request, 'account/friend_request.html', context)


@login_required(login_url = '/')
def add_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    is_friend = Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user)
    if not is_friend:
        add_friend = Friend(user = request.user, users_friend = user)
        add_friend.save()
    return HttpResponseRedirect(reverse('account:account', args = (account_id, )))


@login_required(login_url = '/')
def confirm_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.get(user = user, users_friend = request.user)
    new_friend.confirmed = True
    new_friend.save()
    return HttpResponseRedirect(reverse('account:friends'))



class Text2ImageAPI:
  def __init__(self, url, api_key, secret_key):

    self.URL = url

    self.AUTH_HEADERS = {

    'X-Key': f'Key {api_key}',

    'X-Secret': f'Secret {secret_key}',

  }

  def get_model(self):
    response = requests.get(self.URL + 'key/api/v1/models', 
    headers=self.AUTH_HEADERS)
    data = response.json()
    return data[0]['id']

  def generate(self, prompt, model, images=1, width=1024, height=1024):
    params = {
      "type": "GENERATE",
      "numImages": images,
      "width": width,
      "height": height,
      "generateParams": {
      "query": f"{prompt}"
      }

    }

    data = {
      'model_id': (None, model),
      'params': (None, json.dumps(params), 'application/json')
    }

    response = requests.post(self.URL + 'key/api/v1/text2image/run', 
    headers=self.AUTH_HEADERS, files=data)
    data = response.json()
    return data['uuid']

  def check_generation(self, request_id, attempts=10, delay=10):

    while attempts > 0:
      response = requests.get(self.URL + 'key/api/v1/text2image/status/' + 
      request_id, headers=self.AUTH_HEADERS)
      data = response.json()

      if data['status'] == 'DONE':

        return data['images']

      attempts -= 1
      time.sleep(delay)

@login_required(login_url = '/')
def text2image(text, path_file): # расширение(маска файла) *.jpg на других не тестировал
  api = Text2ImageAPI('https://api-key.fusionbrain.ai/', '58BE4AB7E5F948CA5CD72AAAE0D0391C', '86A3312FCADBE41761EB3CA733B850D0')
  model_id = api.get_model()
  uuid = api.generate(text, model_id)
  images = api.check_generation(uuid)

  image_base64 = images[0] 
  image_data = base64.b64decode(image_base64)
  with open(path_file, "wb") as file:
    file.write(image_data)

  return True





@login_required(login_url = '/')
def delete_friend(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    new_friend = Friend.objects.filter(user = user, users_friend = request.user)|Friend.objects.filter(user = request.user, users_friend = user )
    new_friend.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


#Поиск/отображение всех пользователей
@login_required(login_url = '/')
def find_users(request):
    if request.method == 'POST':
        user_setting = request.user
        search = request.POST.get('search')
        queryset = User.objects.all().exclude(username = request.user)
        if search:
            search_list = search.split(' ')
            if len(search_list) == 2:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) & Q(last_name__iexact=search_list[1])|Q(first_name__iexact=search_list[1]) & Q(last_name__iexact=search_list[0]))
            elif len(search_list) == 1:
                users = queryset.filter(Q(first_name__iexact=search_list[0]) | Q(last_name__iexact=search_list[0]))
            else:
                users = False
        else:
            users = False
    else:
        users = User.objects.all().exclude(username = request.user).order_by("-id")[:20]
    new_friends = Friend.objects.filter(users_friend = request.user, confirmed = False).count()
    context = {
        'users': users,
        "not_confirmed_friends_count": new_friends
    }
    return render(request, 'account/users.html', context)


#Переход на аккаунт другого пользователя
@login_required(login_url = '/')
def account(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

    if Friend.objects.filter(user = request.user, users_friend = user)|Friend.objects.filter(user = user, users_friend = request.user):
        is_friend = False
    else:
        is_friend = True

    if Follower.objects.filter(user = request.user, follower_for = user):
        is_follower = False
    else:
        is_follower = True

    users_friends1 = Friend.objects.filter(user = user, confirmed = True)#[:6]
    users_friends2 = Friend.objects.filter(users_friend = user, confirmed = True)#[:6-len(users_friends1)]

    user_posts = Post.objects.filter(author = user).order_by("-post_time")
    page = request.GET.get('page', 1)
    paginator = Paginator(user_posts, 10)
    try:
      post_list = paginator.page(page)
    except PageNotAnInteger:
      post_list = paginator.page(1)
    except EmptyPage:
      post_list = paginator.page(paginator.num_pages)

    user_following = Follower.objects.filter(user = user)
    context = {'other_user': user, 'user_posts': post_list, 'is_friend': is_friend, "friends1": users_friends1, "friends2": users_friends2, 'is_follower': is_follower, 'user_following': user_following}
    return render(request, 'account/id.html', context)


@login_required(login_url = '/')
def add_follower(request, account_id):
    try:
        user = User.objects.get(id = account_id)
    except:
        raise Http404("Пользователь не найден!")

social_network/templates/base.html
<!doctype  html>
<html  lang="en">
<head>
  {% load static %}
<link rel="shortcut icon" href="../media/static/image/military-helmet-svgrepo-com.svg" type="image/x-icon">
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<link href="{% static 'css/base.css' %}" rel="stylesheet">
{% block style %}
{% endblock %}
<title>
  {% block title %}
  Проект регистрации
  {% endblock%}
</title>
</head>
<body>
  {% block main %}
  {% endblock %}

  {% block footer %}
  
  {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

social_network/templates/menu.html
{% block style %}
<style>
.navbar{
    background-color: rgb(31, 24, 20);
}
*{ margin:0; padding:0; }

ul{ display:inline-block; text-align:center; height:50px; overflow:hidden; }
ul li a{ letter-spacing:0px; text-decoration:none; text-transform:uppercase; color:#FFF; }
ul li{ float:left; height:100%; list-style:none; margin:0 30px; }
ul li *{ display:inline-block; font-size:1.3em; line-height:50px; }
ul li a{ margin-top:-50px; transition:0.3s cubic-bezier(0.1, 0.1, 0.5, 1.4); }
ul li a:hover{ margin-top:0; }
ul li a:before{ content:attr(data-text); display:block; color:#CDF745; }

</style>

{% endblock %}


{% load static %}

  <nav class="navbar navbar-expand-md  sticky-top">
    <div class="container-fluid">
            <a href="{% url 'account:user_account' %}" class="nav-link text-"><img height="80px" class="d-block w-10 rounded" src="{{MEDIA_URL}}static/image/logo.png" href="{% url 'account:user_account' %}" alt="First slide">
             </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'account:user_account' %}" data-text="Мой профиль" class="nav-link text-white ">Мой профиль</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account:friends' %}" data-text="Общий рейтинг" class="nav-link text-white">Общий рейтинг <span class="badge badge-primary" id="new_friends"></span></a>
            </li>
            <li class="nav-item">
              <a href="{% url 'dialogs:messages' %}" data-text="Рейтинг команд" class="nav-link text-white">Рейтинг команд <span class="badge badge-primary" id="messages_count"></span></a>
            </li>
            
            <li class="nav-item">
              <a href="{% url 'registration:logout' %}" data-text="Выйти" class="nav-link text-danger">Выйти</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'registration:login' %}" data-text="Войти" class="nav-link text-white">Войти</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'registration:register' %}" data-text="Зарегистрироваться" class="nav-link text-white">Зарегистрироваться</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="{% static 'js/dialogs/new_messages.js' %}" charset="utf-8"></script>
  <script type="text/javascript">
    var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // Для этих методов токен не будет подставляться в заголовок.
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
  </script>